#Add a tag to the container
services:
  app:
    image: clipper-app-demo
    build:
      context: ./
      target: runner
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
