AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Parent stack that deploys an isolated VPC and a private
             Amazon ECS service in that isolated VPC.
Parameters:
  ECRUri:
    Type: String
    Description: The URI of the private container image to deploy

Resources:

  # The networking configuration. This creates an isolated
  # network specific to this particular environment
  VpcStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: vpc.yml

  # This stack defines the container deployment
  BatchStack:
    Type: AWS::Serverless::Application
    DependsOn: VpcStack
    Properties:
      Location: batch.yml
      Parameters:
        ECRUri: !Ref ECRUri
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateSubnetIds: !GetAtt VpcStack.Outputs.PrivateSubnetIds
        PrivateLinkEndpointSecurityGroup: !GetAtt VpcStack.Outputs.PrivateLinkEndpointSecurityGroup

  S3Stack:
    Type : AWS::Serverless::Application
    Properties:
      Location: source_s3_and_lambda.yml
      Parameters:
        JobQueueArn: !GetAtt BatchStack.Outputs.JobQueueArn
        JobDefinitionArn: !GetAtt BatchStack.Outputs.JobDefinitionArn

  AppStack:
    Type: AWS::Serverless::Application
    DependsOn: [VpcStack, S3Stack, BatchStack]
    Properties:
      Location: app.yml
      Parameters:
        ECRUri: !Ref ECRUri 
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnetIds: !GetAtt VpcStack.Outputs.PublicSubnetIds
        SourceBucket: !GetAtt S3Stack.Outputs.S3BucketName
