AWSTemplateFormatVersion: '2010-09-09'
Description: Set up SNS topic for connecting the server and the batch
             containers
Parameters:
  ServerUrl:
    Type: String
    Description: The url of the server
  AfterUploadEndpoint:
    Type: String
    Default: api/finish_source_processing
    Description: The endpoint of the server
  AfterClipUpdateEndpoint:
    Type: String
    Default: api/finish_clip_processing
    Description: The endpoint of the server

Resources:
  AfterUploadTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "AfterUploadTopic"
      TopicName: "AfterUploadTopic"
      Subscription:
        - Endpoint: !Sub 'https://${ServerUrl}/${AfterUploadEndpoint}'
          Protocol: https
  AfterClipUpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "AfterClipUpdateTopic"
      TopicName: "AfterClipUpdateTopic"
      Subscription:
        - Endpoint: !Sub 'https://${ServerUrl}/${AfterClipUpdateEndpoint}'
          Protocol: https

Outputs:
  AfterUploadTopicArn:
    Value: !Ref AfterUploadTopic
  AfterClipUpdateTopicArn:
    Value: !Ref AfterClipUpdateTopic
