name: Push the Docker image to AWS ECR Repo
on:
  push:
    branches:
      - main
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to Amazon ECR with the latest tag
        id: build-image
        env:
          IMAGE_URL: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_NAME }}:latest
        run: |
          docker build -t $IMAGE_URL src/containers/afterUpload
          docker push $IMAGE_URL
          echo "::set-output name=image::$IMAGE_URL"

      - name: Deploy stack to cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: isolate-vpc-environment
          template: ./cloudformation/parent.yml
          capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
          resolve-s3: true
          parameter-overrides: "ImageUri=${{ steps.build-image.outputs.image }}"
